name: Autofix Pull Requests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

permissions:
  contents: write
  id-token: write

jobs:
  pre-commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR number
        run: echo "PR ${{ github.event.number }} was merged"

      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
            show-progress: true
            lfs: false

      - name: Setup Python 3.10 x64
        uses: actions/setup-python@v5
        with:
            architecture: 'x64'
      - run: |
            pip install pre-commit
            pre-commit run --all

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Formatted code with pre-commit post pr ${{ github.event.number }}"
          git push
